export const VOICES = [
  { name: 'Zephyr', style: 'Bright', cat: 'bright' },
  { name: 'Puck', style: 'Cheerful', cat: 'bright' },
  { name: 'Charon', style: 'Informative', cat: 'calm' },
  { name: 'Kore', style: 'Firm', cat: 'calm' },
  { name: 'Fenrir', style: 'Excitable', cat: 'bright' },
  { name: 'Leda', style: 'Youthful', cat: 'bright' },
  { name: 'Orus', style: 'Corporate', cat: 'calm' },
  { name: 'Aoede', style: 'Breezy', cat: 'calm' },
  { name: 'Callirrhoe', style: 'Easygoing', cat: 'calm' },
  { name: 'Autonoe', style: 'Bright', cat: 'bright' },
  { name: 'Enceladus', style: 'Breathy', cat: 'calm' },
  { name: 'Iapetus', style: 'Clear', cat: 'calm' },
  { name: 'Umbriel', style: 'Easygoing', cat: 'calm' },
  { name: 'Algieba', style: 'Smooth', cat: 'calm' },
  { name: 'Despina', style: 'Smooth', cat: 'calm' },
  { name: 'Erinome', style: 'Clear', cat: 'calm' },
  { name: 'Algenib', style: 'Gravelly', cat: 'calm' },
  { name: 'Rasalgethi', style: 'Informative', cat: 'calm' },
  { name: 'Laomedeia', style: 'Cheerful', cat: 'bright' },
  { name: 'Achernar', style: 'Soft', cat: 'calm' },
  { name: 'Alnilam', style: 'Firm', cat: 'calm' },
  { name: 'Schedar', style: 'Even', cat: 'calm' },
  { name: 'Gacrux', style: 'Mature', cat: 'calm' },
  { name: 'Pulcherrima', style: 'Forward', cat: 'bright' },
  { name: 'Achird', style: 'Friendly', cat: 'bright' },
  { name: 'Zubenelgenubi', style: 'Casual', cat: 'calm' },
  { name: 'Vindemiatrix', style: 'Gentle', cat: 'calm' },
  { name: 'Sadachbia', style: 'Lively', cat: 'bright' },
  { name: 'Sadaltager', style: 'Knowledgeable', cat: 'calm' },
  { name: 'Sulafat', style: 'Raised', cat: 'bright' }
];

export const EMOTIONS = [
  { id: 'neutral', name: 'Neutral', icon: '😐', color: 'slate', desc: 'Natural', prompt: 'Speak naturally' },
  { id: 'happy', name: 'Happy', icon: '😊', color: 'yellow', desc: 'Upbeat', prompt: 'Speak cheerfully' },
  { id: 'sad', name: 'Sad', icon: '😢', color: 'blue', desc: 'Slow', prompt: 'Speak sadly' },
  { id: 'angry', name: 'Angry', icon: '😠', color: 'red', desc: 'Intense', prompt: 'Speak angrily' },
  { id: 'excited', name: 'Excited', icon: '🤩', color: 'pink', desc: 'Energetic', prompt: 'Speak excitedly' },
  { id: 'calm', name: 'Calm', icon: '😌', color: 'emerald', desc: 'Soothing', prompt: 'Speak calmly' },
  { id: 'fearful', name: 'Fearful', icon: '😨', color: 'purple', desc: 'Tense', prompt: 'Speak fearfully' },
  { id: 'surprised', name: 'Surprised', icon: '😲', color: 'orange', desc: 'Shocked', prompt: 'Speak with surprise' },
  { id: 'whisper', name: 'Whisper', icon: '🤫', color: 'cyan', desc: 'Quiet', prompt: 'Speak in a whisper' },
  { id: 'shout', name: 'Shout', icon: '📢', color: 'rose', desc: 'Loud', prompt: 'Speak loudly and shouting' },
  { id: 'cry', name: 'Cry', icon: '😭', color: 'indigo', desc: 'Sobbing', prompt: 'Speak as if crying' },
  { id: 'laugh', name: 'Laugh', icon: '😂', color: 'amber', desc: 'Giggling', prompt: 'Speak with laughter' },
  { id: 'romantic', name: 'Romantic', icon: '❤️', color: 'red', desc: 'Loving', prompt: 'Speak romantically' },
  { id: 'mysterious', name: 'Mystery', icon: '🕵️', color: 'violet', desc: 'Secretive', prompt: 'Speak mysteriously' },
  { id: 'sarcastic', name: 'Sarcastic', icon: '🙄', color: 'lime', desc: 'Ironical', prompt: 'Speak sarcastically' },
  { id: 'serious', name: 'Serious', icon: '🧐', color: 'zinc', desc: 'Formal', prompt: 'Speak seriously' },
  { id: 'friendly', name: 'Friendly', icon: '👋', color: 'teal', desc: 'Warm', prompt: 'Speak friendly' },
  { id: 'professional', name: 'Pro', icon: '💼', color: 'blue', desc: 'Business', prompt: 'Speak professionally' },
  { id: 'dramatic', name: 'Dramatic', icon: '🎭', color: 'fuchsia', desc: 'Theatrical', prompt: 'Speak dramatically' },
  { id: 'tired', name: 'Tired', icon: '😴', color: 'stone', desc: 'Sleepy', prompt: 'Speak tiredly' },
  { id: 'energetic', name: 'Energy', icon: '⚡', color: 'yellow', desc: 'Fast', prompt: 'Speak energetically' },
  { id: 'confident', name: 'Confident', icon: '😎', color: 'sky', desc: 'Bold', prompt: 'Speak confidently' },
  { id: 'shy', name: 'Shy', icon: '🥺', color: 'rose', desc: 'Quiet', prompt: 'Speak shyly' },
  { id: 'hopeful', name: 'Hopeful', icon: '✨', color: 'amber', desc: 'Positive', prompt: 'Speak hopefully' },
  { id: 'bored', name: 'Bored', icon: '😑', color: 'neutral', desc: 'Dull', prompt: 'Speak boredly' },
  { id: 'anxious', name: 'Anxious', icon: '😰', color: 'orange', desc: 'Nervous', prompt: 'Speak anxiously' },
  { id: 'proud', name: 'Proud', icon: '🦁', color: 'gold', desc: 'Grand', prompt: 'Speak proudly' },
  { id: 'guilty', name: 'Guilty', icon: '😔', color: 'slate', desc: 'Regretful', prompt: 'Speak guiltily' },
  { id: 'jealous', name: 'Jealous', icon: '😒', color: 'green', desc: 'Envious', prompt: 'Speak jealously' },
  { id: 'lonely', name: 'Lonely', icon: '🏚️', color: 'blue', desc: 'Isolated', prompt: 'Speak lonely' },
  { id: 'grateful', name: 'Grateful', icon: '🙏', color: 'emerald', desc: 'Thankful', prompt: 'Speak gratefully' },
  { id: 'curious', name: 'Curious', icon: '🤔', color: 'cyan', desc: 'Inquisitive', prompt: 'Speak curiously' },
  { id: 'determined', name: 'Firm', icon: '😤', color: 'red', desc: 'Strong', prompt: 'Speak determinedly' },
  { id: 'relaxed', name: 'Relaxed', icon: '🏖️', color: 'teal', desc: 'Chill', prompt: 'Speak relaxed' },
  { id: 'worried', name: 'Worried', icon: '😟', color: 'yellow', desc: 'Uneasy', prompt: 'Speak worriedly' },
  { id: 'disappointed', name: 'Sad', icon: '😞', color: 'slate', desc: 'Let down', prompt: 'Speak disappointedly' },
  { id: 'inspired', name: 'Inspired', icon: '💡', color: 'amber', desc: 'Creative', prompt: 'Speak inspired' },
  { id: 'silly', name: 'Silly', icon: '🤪', color: 'pink', desc: 'Funny', prompt: 'Speak sillily' },
  { id: 'grumpy', name: 'Grumpy', icon: '😡', color: 'orange', desc: 'Crabby', prompt: 'Speak grumpily' },
  { id: 'peaceful', name: 'Peace', icon: '🕊️', color: 'white', desc: 'Serene', prompt: 'Speak peacefully' },
  { id: 'nostalgic', name: 'Old', icon: '📻', color: 'stone', desc: 'Past', prompt: 'Speak nostalgically' },
  { id: 'brave', name: 'Brave', icon: '🛡️', color: 'red', desc: 'Fearless', prompt: 'Speak bravely' },
  { id: 'kind', name: 'Kind', icon: '🤝', color: 'emerald', desc: 'Gentle', prompt: 'Speak kindly' },
  { id: 'stern', name: 'Stern', icon: '🤨', color: 'zinc', desc: 'Strict', prompt: 'Speak sternly' },
  { id: 'playful', name: 'Play', icon: '🎈', color: 'pink', desc: 'Fun', prompt: 'Speak playfully' },
  { id: 'elegant', name: 'Elegant', icon: '💎', color: 'indigo', desc: 'Fancy', prompt: 'Speak elegantly' },
  { id: 'robotic', name: 'Robot', icon: '🤖', color: 'slate', desc: 'Flat', prompt: 'Speak robotically' },
  { id: 'ghostly', name: 'Ghost', icon: '👻', color: 'white', desc: 'Eerie', prompt: 'Speak ghostly' },
  { id: 'heroic', name: 'Hero', icon: '🦸', color: 'blue', desc: 'Epic', prompt: 'Speak heroically' },
  { id: 'villainous', name: 'Evil', icon: '😈', color: 'purple', desc: 'Dark', prompt: 'Speak villainously' },
  { id: 'cartoon_happy', name: 'Cartoon Joy', icon: '🐣', color: 'yellow', desc: 'Anime', prompt: 'Speak with an exaggerated, high-pitched, bubbly cartoon character voice. Be very expressive.' },
  { id: 'cartoon_angry', name: 'Cartoon Fury', icon: '👹', color: 'red', desc: 'Dramatic', prompt: 'Speak like a funny cartoon villain who is very angry. Use exaggerated emphasis on words.' },
  { id: 'cartoon_scared', name: 'Cartoon Panic', icon: '👻', color: 'purple', desc: 'Hilarious', prompt: 'Speak like a cartoon character who is completely panicking and trembling. High energy and jittery.' },
  { id: 'monster', name: 'Monster', icon: '👹', color: 'red', desc: 'Beast', prompt: 'Speak with a deep, growling, monstrous voice. Very low pitch and terrifying.' },
  { id: 'child', name: 'Child', icon: '👶', color: 'sky', desc: 'Cute', prompt: 'Speak with a high-pitched, innocent, and sweet child voice. Pure and soft.' },
  { id: 'alien', name: 'Alien', icon: '👽', color: 'lime', desc: 'Unique', prompt: 'Speak with a strange, warbling, extraterrestrial voice. Use unusual inflections.' },
  { id: 'cartoon_silly', name: 'Silly/Funny', icon: '🤡', color: 'orange', desc: 'Goofy', prompt: 'Speak like a goofy, silly cartoon sidekick. Use funny inflections and high energy. Be extremely entertaining.' },
  { id: 'witch', name: 'Witch/Old', icon: '🧙‍♀️', color: 'indigo', desc: 'Cracked', prompt: 'Speak like a mysterious old witch or an eccentric older character. Use a crackly, aged, and slightly rasping voice.' },
  { id: 'giant', name: 'Goofy Giant', icon: '🧱', color: 'stone', desc: 'Deep', prompt: 'Speak like a slow-witted, large, and friendly giant. Use a very deep, slow, and resonant voice.' },
  { id: 'scientist', name: 'Mad Scientist', icon: '🧪', color: 'emerald', desc: 'Manic', prompt: 'Speak like an eccentric, high-strung mad scientist. Use erratic pacing and sudden bursts of energy.' },
  { id: 'crying', name: 'Crying', icon: '😭', color: 'blue', desc: 'Emotional', prompt: 'Speak while sobbing and being completely heartbroken. The voice should tremble and break with sadness.' },
  { id: 'sneaky', name: 'Sneaky', icon: '👣', color: 'slate', desc: 'Suspicious', prompt: 'Speak in a low, conspiratorial whisper. Like you are a spy or a thief hiding in the shadows.' },
  { id: 'sassy', name: 'Sassy', icon: '💅', color: 'pink', desc: 'Confident', prompt: 'Speak with a sharp, witty, and confident sassy attitude. Use lots of personality and emphasis.' },
  { id: 'cartoon_hero', name: 'Heroic Hero', icon: '🦸‍♂️', color: 'blue', desc: 'Brave', prompt: 'Speak like a classic, noble cartoon superhero. Deep, confident, and inspiring voice.' },
  { id: 'cartoon_villain_laugh', name: 'Evil Cackle', icon: '🦹', color: 'purple', desc: 'Manic', prompt: 'Speak like a villain having a maniacal laughing fit. Very expressive and slightly unhinged.' },
  { id: 'cartoon_ninja', name: 'Swift Ninja', icon: '🥷', color: 'slate', desc: 'Quick', prompt: 'Speak in a fast, focused, and disciplined ninja voice. Sharp and precise delivery.' },
  { id: 'cartoon_pirate', name: 'Hearty Pirate', icon: '🏴‍☠️', color: 'orange', desc: 'Rough', prompt: 'Speak like a classic cartoon pirate. Gruff, hearty, and full of seafaring slang.' },
  { id: 'cartoon_fairy', name: 'Tiny Fairy', icon: '🧚', color: 'pink', desc: 'Light', prompt: 'Speak with a very high-pitched, delicate, and tinkling fairy voice. Soft and magical.' },
  { id: 'cartoon_dragon', name: 'Fiery Dragon', icon: '🐲', color: 'red', desc: 'Power', prompt: 'Speak with a deep, rumbling, and powerful dragon voice. Slightly smoky and intimidating.' },
  { id: 'cartoon_robot_glitch', name: 'Glitchy Bot', icon: '📟', color: 'cyan', desc: 'Broken', prompt: 'Speak like a robot that is malfunctioning or glitching. Use stuttered delivery and variable pitch.' },
  { id: 'cartoon_detective', name: 'Noir Sleuth', icon: '🕵️‍♂️', color: 'zinc', desc: 'Cool', prompt: 'Speak in a gravelly, cool, and mysterious noir detective voice. Very rhythmic and moody.' },
  { id: 'cartoon_explorer', name: 'Brave Scout', icon: '🏕️', color: 'emerald', desc: 'Eager', prompt: 'Speak with an enthusiastic, high-energy, and adventurous young explorer voice.' },
  { id: 'cartoon_king', name: 'Pompous King', icon: '👑', color: 'gold', desc: 'Royal', prompt: 'Speak with a very posh, slightly arrogant, and commanding royal voice.' },
  { id: 'cartoon_jester', name: 'Wild Jester', icon: '🃏', color: 'yellow', desc: 'Funny', prompt: 'Speak with an erratic, high-pitched, and playful jester voice. Lots of giggles and jumps.' },
  { id: 'cartoon_warrior', name: 'Battle Grunt', icon: '⚔️', color: 'red', desc: 'Strong', prompt: 'Speak like a powerful warrior in the heat of battle. Gravelly, breathless, and intense.' },
  { id: 'cartoon_space', name: 'Star Captain', icon: '🚀', color: 'indigo', desc: 'Epic', prompt: 'Speak with a dramatic, booming, and authoritative space captain voice. Very theatrical.' },
  { id: 'cartoon_zombie', name: 'Funny Zombie', icon: '🧟', color: 'green', desc: 'Dazed', prompt: 'Speak like a cartoon zombie that is slow, dazed, and groaning words out.' },
  { id: 'cartoon_ghost_friendly', name: 'Pudge Ghost', icon: '👻', color: 'sky', desc: 'Sweet', prompt: 'Speak with a soft, breathy, and friendly ghost voice. Very cute and gentle.' },
  { id: 'cartoon_cowboy', name: 'Lone Rider', icon: '🤠', color: 'amber', desc: 'Drawl', prompt: 'Speak with a slow, Southern cowboy drawl. Cool, calm, and collected.' },
  { id: 'cartoon_mermaid', name: 'Sea Singer', icon: '🧜‍♀️', color: 'blue', desc: 'Dreamy', prompt: 'Speak with a dreamy, melodic, and slightly echoing underwater voice.' },
  { id: 'cartoon_dwarf', name: 'Grumpy Miner', icon: '⚒️', color: 'stone', desc: 'Gravel', prompt: 'Speak with a deep, gravelly, and grumpy dwarf-like voice. Strong accent.' },
  { id: 'cartoon_elf', name: 'Swift Elf', icon: '🧝', color: 'forest', desc: 'Elegant', prompt: 'Speak with a light, graceful, and highly articulate elven voice.' },
  { id: 'cartoon_alien_cute', name: 'Bip-Bop', icon: '👾', color: 'lime', desc: 'Small', prompt: 'Speak with a very high-pitched, chirpy, and adorable small alien voice.' }
];
